<?php

namespace SearchBundle\Repository;

use

/**
 * AgendaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
//use Doctrine\ORM\Mapping;

class SearchRepository /*extends \Doctrine\ORM\EntityRepository*/
{

    public function Search($bdd, $requete)
    {
        // la requête, que vous devez maintenant comprendre et modifier;)
        $em = $this->getDoctrine()->getManager();
        $query = $bdd->prepare("SELECT post.titre, post.contenu, categorie_plateforme.nom
                            FROM post, categorie_plateforme
                            WHERE post.titre, post.contenu, categorie_plateforme.nom
                            LIKE '%$requete%'
                            ORDER BY id DESC") or die ();

        //on execute la requete
        $query->execute(array(
            'requete' => $requete
        ));
    }
}
