<?php

namespace SearchBundle\Repository;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;

/**
 * AgendaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
//use Doctrine\ORM\Mapping;

class SearchRepository extends \Doctrine\ORM\EntityRepository
{

    public function Search($bdd, $requete)
    {
        $em = $this->getDoctrine()->getmanager();

        // la requête, que vous devez maintenant comprendre et modifier;)
        $query = $bdd->prepare("SELECT titre, contenu, nom 
                                FROM post, categorie_plateforme 
                                WHERE post.parent_id = categorie_plateforme.parent_id 
                                AND contenu = '$requete' 
                                OR titre = '$requete' 
                                OR nom = '$requete' 
                                ORDER BY post.id DESC") or die ('La requète ne se fait pas correctement');

        //on execute la requete
        $query->execute(array(
            'requete' => $requete
        ));
    }
}
