HarasBundle\Entity\Article:
    type: entity
    table: null
    repositoryClass: HarasBundle\Repository\ArticleRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
            unique: true
        createdAt:
            type: date
    manyToOne:
        title:
            targetEntity: Text
            inversedBy: articles_title
            nullable: true
            joinColumn:
                name: title_id
                referencedColumnName: id
        content:
            targetEntity: Text
            inversedBy: articles_content
            nullable: true
            joinColumn:
                name: content_id
                referencedColumnName: id
        structure:
            targetEntity: ArticleStructure
            joinColumn:
                name: structure_id
                referencedColumnName: id
    manyToMany:
        medias:
            targetEntity: Media
            joinTable:
                name: articles_medias
                joinColumns:
                    article_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    media_id:
                        referencedColumnName: id
        pages:
            targetEntity: Page
            mappedBy: articles
    lifecycleCallbacks: {  }
