HarasBundle\Entity\ArticleStructure:
    type: entity
    table: null
    repositoryClass: HarasBundle\Repository\ArticleStructureRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
            unique: true
    lifecycleCallbacks: {  }
