user_index:
    path:     /
    defaults: { _controller: "UserBundle:User:index" }
    methods:  GET
user_show:
    path:     /{id}/show
    defaults: { _controller: "UserBundle:User:show" }
    methods:  GET
user_new:
    path:     /new
    defaults: { _controller: "UserBundle:User:new" }
    methods:  [GET, POST]
user_edit:
    path:     /{id}/edit
    defaults: { _controller: "UserBundle:User:edit" }
    methods:  [GET, POST]

user_delete:
    path:     /{id}/delete
    defaults: { _controller: "UserBundle:User:delete" }
    methods:  DELETE

user_desactive:
    path:     /{id}/desactive
    defaults: { _controller: "UserBundle:User:desactive" }
    methods:  [GET, POST]

user_reactive:
    path:     /{id}/reactive
    defaults: { _controller: "UserBundle:User:reactive" }
    methods:  [GET, POST]

user_showAllUserDesactive:
    path:     /showAllUserDesactive
    defaults: { _controller: "UserBundle:User:showInactiveUser:" }
    methods:  [GET, POST]