ForumBundle\Entity\CategoriePlateforme:
    type: entity
    table: null
#    repositoryClass: ForumBundle\Repository\CategoriePlateformeRepository
    repositoryClass: SearchBundle\Repository\SearchRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nom:
            type: string
            length: 255
        actif:
            type: boolean

    oneToMany:
        enfant:
          targetEntity: ForumBundle\Entity\CategoriePlateforme
          mappedBy: parent
    manyToOne:
        parent:
          targetEntity: ForumBundle\Entity\CategoriePlateforme
          inversedBy: enfant

    lifecycleCallbacks: {  }