#**********************************#
#       Gestion newsletters        #
#**********************************#

newsletter_index:
    path:     /
    defaults: { _controller: "PlateFormeBundle:NewsLetter:index" }
    methods:  GET

newsletter_show:
    path:     /{id}/show
    defaults: { _controller: "PlateFormeBundle:NewsLetter:show" }
    methods:  GET

newsletter_new:
    path:     /new
    defaults: { _controller: "PlateFormeBundle:NewsLetter:new" }
    methods:  [GET, POST]

newsletter_edit:
    path:     /{id}/edit
    defaults: { _controller: "PlateFormeBundle:NewsLetter:edit" }
    methods:  [GET, POST]

newsletter_send:
    path:     /newsletter_send/{id}
    defaults: { _controller: "PlateFormeBundle:NewsLetter:sendMail" }
    methods: [GET, POST]
    requirements:
        id:  \d+

newsletter_delete:
    path:     /{id}/delete
    defaults: { _controller: "PlateFormeBundle:NewsLetter:delete" }
    requirements:
        id:  \d+

#**********************************#
#       Gestion                    #
#       Abonnement                 #
#       newsletters                #
#**********************************#
abonnement_newsletter:
    path:     /abonnement/new
    defaults: { _controller: "PlateFormeBundle:AbonnementNewsLetter:abonnementNewsletter" }
    methods:  [GET, POST]


desabonnement_newsletter:
    path:     /desabonnement/
    defaults: { _controller: "PlateFormeBundle:AbonnementNewsLetter:desabonnementNewsletter" }
    methods:  [GET, POST]


