philosophie_index:
    path:     /
    defaults: { _controller: "PlateFormeBundle:Philosophie:index" }
    methods:  GET

philosophie_show:
    path:     /{id}/show
    defaults: { _controller: "PlateFormeBundle:Philosophie:show" }
    methods:  GET

philosophie_new:
    path:     /new
    defaults: { _controller: "PlateFormeBundle:Philosophie:new" }
    methods:  [GET, POST]

philosophie_edit:
    path:     /{id}/edit
    defaults: { _controller: "PlateFormeBundle:Philosophie:edit" }
    methods:  [GET, POST]

philosophie_delete:
    path:     /{id}/delete
    defaults: { _controller: "PlateFormeBundle:Philosophie:delete" }
    methods:  DELETE
