philosophie_show:
    path:     /show
    defaults: { _controller: "PlateFormeBundle:Philosophie:show" }
    methods:  GET


philosophie_edit:
    path:     /{id}/edit
    defaults: { _controller: "PlateFormeBundle:Philosophie:edit" }
    methods:  [GET, POST]