post_index:
    path:     /
    defaults: { _controller: "PlateFormeBundle:Post:index" }
    methods:  GET

post_show:
    path:     /{id}/show
    defaults: { _controller: "PlateFormeBundle:Post:show" }
    methods:  GET

post_showAllPost:
    path:     /{id}/showAllPost
    defaults: { _controller: "PlateFormeBundle:Post:showAllPost" }
    methods:  GET


post_new:
    path:     /new
    defaults: { _controller: "PlateFormeBundle:Post:new" }
    methods:  [GET, POST]

post_edit:
    path:     /{id}/edit
    defaults: { _controller: "PlateFormeBundle:Post:edit" }
    methods:  [GET, POST]

post_delete:
    path:     /{id}/delete
    defaults: { _controller: "PlateFormeBundle:Post:delete" }
    methods:  DELETE
