page_index:
    path:     /
    defaults: { _controller: "HarasBundle:Page:index" }
    methods:  GET

page_show:
    path:     /{name}/show
    defaults: { _controller: "HarasBundle:Page:show" }
    methods:  GET

page_new:
    path:     /new
    defaults: { _controller: "HarasBundle:Page:new" }
    methods:  [GET, POST]

page_edit:
    path:     /{name}/edit
    defaults: { _controller: "HarasBundle:Page:edit" }
    methods:  [GET, POST]

page_delete:
    path:     /{name}/delete
    defaults: { _controller: "HarasBundle:Page:delete" }
    methods:  DELETE