##########################################
########   Routes Post CRUD  #############
##########################################

post_index:
    path:     /
    defaults: { _controller: "ForumBundle:Post:index" }
    methods:  GET

post_show:
    path:     /{id}/show
    defaults: { _controller: "ForumBundle:Post:show" }
    methods:  GET

post_showAllPost:
    path:     /{id}/showAllPost
    defaults: { _controller: "ForumBundle:Post:showAllPost" }
    methods:  GET

post_new:
    path:     /{cat}/{id}/new
    defaults: { _controller: "ForumBundle:Post:new" }
    methods:  [GET, POST]

post_newParent:
    path:     /{cat}/new
    defaults: { _controller: "ForumBundle:Post:newParent" }
    methods:  [GET, POST]

post_edit:
    path:     /{id}/edit
    defaults: { _controller: "ForumBundle:Post:edit" }
    methods:  [GET, POST]

post_desactive:
    path:     /{id}/desactive
    defaults: { _controller: "ForumBundle:Post:desactive" }
    methods:  [GET, POST]

post_resactive:
    path:     /{id}/resactive
    defaults: { _controller: "ForumBundle:Post:reactive" }
    methods:  [GET, POST]

post_showAllPostDesactive:
    path:     /showAllPostDesactive
    defaults: { _controller: "ForumBundle:Post:showInactivePost" }
    methods:  [GET, POST]

post_delete:
    path:     /{id}/delete
    defaults: { _controller: "ForumBundle:Post:delete" }
    methods:  DELETE
