haras_page:
    resource: "@HarasBundle/Resources/config/routing/page.yml"
    prefix:   /page

haras_article:
    resource: "@HarasBundle/Resources/config/routing/article.yml"
    prefix:   /article

haras_media:
    resource: "@HarasBundle/Resources/config/routing/media.yml"
    prefix:   /media

haras_text:
    resource: "@HarasBundle/Resources/config/routing/text.yml"
    prefix:   /text

#Route general
haras_get_page:
    path:     /{name}/{langChoice}
    defaults: 
        _controller: HarasBundle:Page:getPage
        name: homepage
        langChoice: null