haras_page:
    resource: "@HarasBundle/Resources/config/routing/page.yml"
    prefix:   /page

haras_article:
    resource: "@HarasBundle/Resources/config/routing/article.yml"
    prefix:   /article

haras_media:
    resource: "@HarasBundle/Resources/config/routing/media.yml"
    prefix:   /media

haras_text:
        resource: "@HarasBundle/Resources/config/routing/text.yml"
        prefix:   /text

haras_homepage:
    path:     /
    defaults: { _controller: HarasBundle:Index:index }

haras_template:
    path:     /template
    defaults: { _controller: HarasBundle:Template:template }

haras_contact:
    path:     /contact
    defaults: { _controller: HarasBundle:Contact:contact }

