<?php

namespace PlateFormeBundle\Repository;

/**
 * AbonnementNewsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AbonnementNewsRepository extends \Doctrine\ORM\EntityRepository
{
}
