<?php

namespace PlateFormeBundle\Repository;

/**
 * MessagerieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessagerieRepository extends \Doctrine\ORM\EntityRepository
{
}
