<?php

namespace PlateFormeBundle\Repository;

/**
 * PhilosophieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PhilosophieRepository extends \Doctrine\ORM\EntityRepository
{
}
