imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@HarasBundle/Resources/config/services.yml" }
    - { resource: "@PlateFormeBundle/Resources/config/services.yml" }
    - { resource: "@UserBundle/Resources/config/services.yml" }
    - { resource: "@CalendarBundle/Resources/config/services.yml" }
    - { resource: "@ForumBundle/Resources/config/services.yml" }
    - { resource: "@SearchBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: fr
    medias_directory: '%kernel.root_dir%/../src/HarasBundle/Resources/public/media'
    web_directory: '%kernel.root_dir%/../web/'
    articles_per_page: 4
    pictures_directory: '%kernel.root_dir%/../web/uploads/pictures'

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        gc_probability: 0
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

        dql:
            string_functions:
                regexp: DoctrineExtensions\Query\Mysql\Regexp

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: UserBundle\Entity\User
    registration:
        form:
            type: UserBundle\Form\RegistrationType
            # if you are using Symfony < 2.8 you should use the type name instead
            # type: app_user_registration
    from_email:
        address: haras@haras.com
        sender_name: "Haras"
    profile:
        form:
            type: UserBundle\Form\ProfileType

# fos_user:
#     db_driver: orm # other valid values are 'mongodb' and 'couchdb'
#     firewall_name: main
#     user_class: TR\UserBundle\Entity\User
#     registration:
#         confirmation:
#             enabled: true
#         form:
#             type: TR\UserBundle\Form\RegistrationType
#     from_email:
#         address: "%mailer_user%"
#         sender_name: "%mailer_name%"

twig:
    exception_controller:  HarasBundle:Exception:showException

mobile_detect:
    redirect:
        mobile: ~
        tablet: ~
    switch_device_view: ~

# Gestion BBCode
# CKeditor configuration
ivory_ck_editor:
#    base_path: "ckeditor"
#    js_path:   "/bundles/mediaproject/ivoryckeditor/ckeditor.js"
    plugins:
    default_config: my_config
    configs:
        my_config:
            toolbar:                    [ [ 'Preview' ], [ 'Cut','Copy','Paste','PasteText','PasteFromWord','-','Undo','Redo' ], [ 'Find','Replace','-','SelectAll','-','SpellChecker', 'Scayt' ], "/", [ 'Bold','Italic','Underline','Strike', 'Blockquote','Subscript','Superscript','-','RemoveFormat' ], [ 'NumberedList','BulletedList','-','Outdent','Indent','-','-','JustifyLeft','JustifyCenter','JustifyRight','JustifyBlock' ], [ 'Link','Unlink','Anchor' ], [ 'pbckcode', 'Smiley', 'Image', 'Video', 'Table','SpecialChar','Iframe' ], '/', [ 'Styles', 'Format','Font','FontSize' ], [ 'TextColor','BGColor' ], [ 'RemoveFormat' ], [ 'Maximize' ] ]
            language: %locale%
            uiColor: #FFA500

# Gestion de la pagination
# Knp paginator configuration
knp_paginator:
    page_range: 5                      # default page range used in pagination control
    default_options:
        page_name: page                # page query parameter name
        sort_field_name: sort          # sort field query parameter name
        sort_direction_name: direction # sort direction query parameter name
        distinct: true                 # ensure distinct results, useful when ORM queries are using GROUP BY statements
    template:
        pagination: ForumBundle:post:pagination.html.twig     # pagination controls template
        sortable: KnpPaginatorBundle:Pagination:sortable_link.html.twig # sort link template