##########################################
########   Routes Calendrier   ###########
##########################################

calendar:
    resource: "@CalendarBundle/Resources/config/routing.yml"
    prefix:   /plateforme

##########################################
########   Routes Plateforme   ###########
##########################################

plate_forme:
    resource: "@PlateFormeBundle/Resources/config/routing.yml"
    prefix:   /plateforme

##########################################
########   Routes User   #################
##########################################

fos_user:
    resource: "@UserBundle/Resources/config/routing/user.yml"
    prefix:   /plateforme/admin/user

##########################################
########   Route Homepage  ###############
##########################################

haras:
    resource: "@HarasBundle/Resources/config/routing.yml"
    prefix:   /

