plate_forme:
    resource: "@PlateFormeBundle/Resources/config/routing.yml"
    prefix:   /plateforme

#fos_user:
#    resource: "@UserBundle/Resources/config/routing/all.xml"
#    prefix:   /

haras:
    resource: "@HarasBundle/Resources/config/routing.yml"
    prefix:   /

