##########################################
########   Routes User   #################
##########################################

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /plateforme

##########################################
###########   Routes Forum   #############
##########################################

forum:
    resource: "@ForumBundle/Resources/config/routing.yml"
    prefix:   /plateforme

##########################################
########   Routes Calendrier   ###########
##########################################

calendar:
    resource: "@CalendarBundle/Resources/config/routing.yml"
    prefix:   /plateforme

##########################################
########   Routes Plateforme   ###########
##########################################

plate_forme:
    resource: "@PlateFormeBundle/Resources/config/routing.yml"
    prefix:   /plateforme

##########################################
########   Route Homepage  ###############
##########################################

haras:
    resource: "@HarasBundle/Resources/config/routing.yml"
    prefix:   /