
##########################################
########   Routes Search   ###############
##########################################
#search:
#    resource: "@SearchBundle/Resources/config/routing.yml"
#    prefix:   /plateforme
#    methods:  [GET, POST]

plate_forme_searchController:
    path:     /plateforme/search
    defaults: { _controller: SearchBundle:SearchEngine:search }
    methods:  [GET, POST]

##########################################
########   Routes User   #################
##########################################

fos_user:
    resource: "@UserBundle/Resources/config/routing/user.yml"
    prefix:   /plateforme/admin/user

##########################################
###########   Routes Forum   #############
##########################################

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /plateforme

##########################################
###########   Routes Forum   #############
##########################################

forum:
    resource: "@ForumBundle/Resources/config/routing.yml"
    prefix:   /plateforme

##########################################
########   Routes Calendrier   ###########
##########################################

calendar:
    resource: "@CalendarBundle/Resources/config/routing.yml"
    prefix:   /plateforme

##########################################
########   Routes Plateforme   ###########
##########################################

plate_forme:
    resource: "@PlateFormeBundle/Resources/config/routing.yml"
    prefix:   /plateforme


haras:
    resource: "@HarasBundle/Resources/config/routing.yml"
    prefix:   /

