# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_USER:        ROLE_USER
        ROLE_MODERATEUR:  ROLE_USER
        ROLE_ADMIN:       ROLE_MODERATEUR

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                check_path: fos_user_security_check
                default_target_path: /
            # [redirection après login]
                success_handler: redirect.after.login

            logout:
                path: fos_user_security_logout
                target: plate_forme_homepage
            # [redirection apres logout]
                success_handler: redirect.after.logout
            anonymous:    true



            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
    access_control:
#        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/plateforme/?$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/plateforme/(login|register), role: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/plateforme/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/plateforme/admin/, role: ROLE_ADMIN }
        - { path: ^/plateforme/categorieplateforme, role: ROLE_ADMIN }
        - { path: ^/plateforme/.+, role: ROLE_USER }


          # PAGES ACCESSIBLES AUX ADMINISTRATEURS
#        - { path: ^/admin, role: ROLE_ADMIN }



