##########################################
############   Routes Search   ###########
##########################################

plate_forme_search:
    path:     /plateforme/search
    defaults: { _controller: SearchBundle:Default:index }
