##########################################
############   Routes Search   ###########
##########################################

plate_forme_search:
    path:     /search
    defaults: { _controller: SearchBundle:Default:index }
