<?php

namespace HarasBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ArticleStructureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleStructureRepository extends EntityRepository
{
}
