<?php

namespace HarasBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends EntityRepository
{
	public function findArticles($pageNb, $page, $limit)
	{
        $offset = ($pageNb-1)*$limit;
        $qb = $this->createQueryBuilder('a')
            ->select('a')
            ->join('a.pages','p')
            ->where('p = :page')
            ->setParameter('page', $page)
            ->orderBy('a.createdAt', 'DESC')
            ->setFirstResult( $offset )
            ->setMaxResults( $limit );
   	    return $qb->getQuery()->getResult();
	}
}
