plate_forme_post:
    resource: "@ForumBundle/Resources/config/routing/post.yml"
    prefix:   /post

plate_forme_categorieplateforme:
    resource: "@ForumBundle/Resources/config/routing/categorieplateforme.yml"
    prefix:   /categorieplateforme