plate_forme_post:
    resource: "@PlateFormeBundle/Resources/config/routing/post.yml"
    prefix:   /post

plate_forme_homepage:
    path:     /
    defaults: { _controller: PlateFormeBundle:Default:index }
