plate_forme_homepage:
    path:     /
    defaults: { _controller: PlateFormeBundle:Default:index }

plate_forme_admin:
    path:     /admin/
    defaults: { _controller: PlateFormeBundle:Default:admin }