plate_forme_homepage:
    path:     /
    defaults: { _controller: PlateFormeBundle:Default:index }

plate_forme_admin:
    path:     /admin/
    defaults: { _controller: PlateFormeBundle:Default:admin }

plate_forme_moderateur:
    path:     /moderateur/
    defaults: { _controller: PlateFormeBundle:Default:moderateur }

#plate_forme_philosophie_user:
#    path:     /philosophie/
#    defaults: { _controller: PlateFormeBundle:Default:philosophie }

plate_forme_philosophie:
    resource: "@PlateFormeBundle/Resources/config/routing/philosophie.yml"
    prefix:   /philosophie/

plate_forme_register:
    resource: "@UserBundle/Resources/config/routing/all.xml"