plate_forme_homepage:
    path:     /
    defaults: { _controller: PlateFormeBundle:Default:index }

plate_forme_register:
    resource: "@UserBundle/Resources/config/routing/all.xml"

#plate_forme_profil:
#    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"

