plate_forme_homepage:
    path:     /
    defaults: { _controller: PlateFormeBundle:Default:index }

# ------------------------ plate_forme_agenda: ------------------------------
plate_forme_agenda:
      resource: "@PlateFormeBundle/Resources/config/routing/agenda.yml"
      prefix:   /agenda
      options:
          expose: true


#FOS JS Routing ==> permet de convertir route php en js
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
    prefix:   /