plate_forme_homepage:
    path:     /
    defaults: { _controller: PlateFormeBundle:Default:index }

# ------------------------ Route Calendar -----------------------------------
# CALENDAR ADMIN
plate_forme_calendar:
    path:     /calendar
    defaults: { _controller: PlateFormeBundle:Default:calendar }

#CALENDAR USER NON SELECTABLE
plate_forme_calendar_index:
    path:     /calendar_index
    defaults: { _controller: PlateFormeBundle:Default:calendar_index }


# ------------------------ plate_forme_agenda: ------------------------------
plate_forme_agenda:
        resource: "@PlateFormeBundle/Resources/config/routing/agenda.yml"
        prefix:   /agenda


#FOS JS Routing ==> permet de convertir route php en js
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
    prefix:   /