<?php

namespace ForumBundle\Repository;

/**
 * CategoriePlateformeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoriePlateformeRepository extends \Doctrine\ORM\EntityRepository
{
    public function getSousCategorie(){
//        $sql = 'SELECT * FROM categorie_plateforme WHERE parent_id is NOT null and actif = 1';
//        return $this->getEntityManager()->getConnection()->executeQuery($sql)->fetchAll();
        $qb = $this->createQueryBuilder('a')
        ->select('a')
        ->where('a.parent IS NOT NULL')
        ->andWhere('a.actif = 1')
        ->add('orderBy', 'a.nom ASC');
   	    return $qb->getQuery()->getResult();
    }

    public function getNameCateg(){
//      Récupération des noms des catégories du Haras Bundle
        $nameSection = ['section1name', 'section2name', 'section3name', 'section4name'];
        $sql = 'SELECT text_fr, text.name FROM text WHERE text.name IN (\'section1name\', \'section2name\', \'section3name\', \'section4name\')';

        return $this->getEntityManager()->getConnection()->executeQuery($sql)->fetchAll();
    }

    public function findPost($limit, $requete, Post $post) // CategoriePlateforme $categoriePlateforme
    {
//        Alias 's' = class searchrepository
//        Alias 'p' = jointure parent_id


//        $qb = $this->createQueryBuilder(from POst, from categorie, from haras)
//            ->select('s.titre')
//            ->orderBy('s.date_create', 'DESC')
//            ->setMaxResults( $limit );
//        return $qb->getQuery()->getResult();
    }
}
